apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: nfs-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  storageClassName: csi-manila-nfs
